---
name: Run tests
on:
  pull_request:
  push:
    branches:
      - trunk

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: nvim-neorocks/nvim-busted-action@v1
        with:
          nvim_version: stable
